"use client";

import Image from "next/image";
import { ArrowRight, CalendarDays, CircleUserRound, CreditCard, Heart, LayoutDashboard, Menu, MessageCircle, MoreHorizontal, Search, UsersRound, WalletCards } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

const sessions = [
  { time: "09:00", title: "Reformer Fondations", coach: "Sarah", count: "5/6" },
  { time: "10:30", title: "Pilates au sol", coach: "Nesrine", count: "8/10" },
  { time: "14:00", title: "Reformer Flow", coach: "Sarah", count: "6/6" },
  { time: "17:30", title: "Séance individuelle", coach: "Lina", count: "1/1" },
];

const clients = [
  { initials: "LM", name: "Lina Messaoudi", plan: "Équilibre · 10 séances", remaining: "7 restantes" },
  { initials: "SA", name: "Sofia Amrane", plan: "Reformer · 5 séances", remaining: "2 restantes" },
  { initials: "NB", name: "Nadia Belkacem", plan: "Cours individuel", remaining: "4 restantes" },
];

function Lotus({ className = "h-9 w-9" }: { className?: string }) {
  return <svg viewBox="0 0 80 58" className={className} fill="none" aria-hidden="true"><g stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M40 49C28 38 27 22 40 6c13 16 12 32 0 43Z"/><path d="M37 47C22 43 14 32 14 18c14 2 24 11 27 25"/><path d="M43 47c15-4 23-15 23-29-14 2-24 11-27 25"/><path d="M35 49C22 52 10 48 4 39c11-6 24-5 33 5"/><path d="M45 49c13 3 25-1 31-10-11-6-24-5-33 5"/></g></svg>;
}

function BrandLockup({ light = false, compact = false }: { light?: boolean; compact?: boolean }) {
  return <div className={`flex items-center gap-3 ${light ? "text-[#e1be79]" : "text-[#191919]"}`}><Lotus className={compact ? "h-8 w-10" : "h-10 w-12"}/><div className="leading-none"><div className={`${compact ? "text-base" : "text-xl"} brand-wide font-light`}>PILATES CENTER</div><div className="mt-1.5 flex items-center gap-2 text-[9px] tracking-[.34em] text-[#b7893b]"><span className="h-px w-4 bg-current"/> SCULPTFIT CENTER <span className="h-px w-4 bg-current"/></div></div></div>;
}

function PreviewSwitcher() {
  return <div className="sticky top-0 z-[60] flex items-center justify-between border-b border-white/10 bg-[#070707] px-4 py-3 text-white shadow-xl sm:px-8"><div className="hidden text-sm text-white/60 sm:block">Modèle d’identité visuelle</div><TabsList className="mx-auto h-11 rounded-full border border-[#b7893b]/40 bg-[#17130e] p-1"><TabsTrigger value="site" className="rounded-full px-5 text-sm text-white/60 data-[state=active]:bg-[#b7893b] data-[state=active]:text-black">Site public</TabsTrigger><TabsTrigger value="crm" className="rounded-full px-5 text-sm text-white/60 data-[state=active]:bg-[#b7893b] data-[state=active]:text-black">Aperçu CRM</TabsTrigger></TabsList><div className="hidden text-xs uppercase tracking-[.2em] text-[#b7893b] sm:block">Force · Équilibre · Bien-être</div></div>;
}

function PublicSite() {
  return <div className="min-h-screen bg-[#f8f2e9] text-[#1d1d1d]">
    <header className="border-b border-[#cdae72]/30 bg-[#fcf8f1]/95"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><BrandLockup compact/><nav className="hidden items-center gap-8 text-sm lg:flex"><a href="#studio">Le studio</a><a href="#pratiques">Nos pratiques</a><a href="#planning">Planning</a><a href="#tarifs">Tarifs</a></nav><div className="flex items-center gap-2"><button className="hidden rounded-full px-4 py-2.5 text-sm sm:block">Espace cliente</button><button className="rounded-full bg-[#111] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#b7893b] hover:text-black">Réserver</button><button className="p-2 lg:hidden" aria-label="Ouvrir le menu"><Menu/></button></div></div></header>
    <main>
      <section id="studio" className="mx-auto grid min-h-[680px] max-w-7xl items-center gap-10 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-20"><div className="relative z-10"><div className="mb-8 inline-flex items-center gap-3 text-xs font-semibold uppercase tracking-[.28em] text-[#9a712e]"><span className="h-px w-10 bg-[#b7893b]"/> Studio féminin à Alger</div><h1 className="max-w-3xl font-serif text-[clamp(3.4rem,7vw,6.8rem)] font-light leading-[.92] tracking-[-.04em]">La force dans<br/><em className="font-light text-[#b7893b]">l’équilibre.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#676056]">Pilates au sol et Reformer dans un espace pensé pour vous recentrer, progresser et prendre soin de votre corps.</p><div className="mt-9 flex flex-wrap items-center gap-4"><button className="group inline-flex items-center gap-3 rounded-full bg-[#b7893b] px-6 py-4 font-semibold text-black transition hover:bg-[#d7b66f]">Découvrir nos cours <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></button><button className="rounded-full border border-[#b7893b]/50 px-6 py-4 font-semibold">Voir le planning</button></div><div className="mt-12 grid max-w-xl grid-cols-3 gap-4 border-t border-[#cdae72]/35 pt-7">{[["4","pratiques"],["100%","féminin"],["10","places max."]].map(([value,label])=><div key={label}><div className="font-serif text-3xl text-[#99702d]">{value}</div><div className="mt-1 text-xs uppercase tracking-[.16em] text-[#71695e]">{label}</div></div>)}</div></div><div className="relative mx-auto h-[610px] w-full max-w-[520px] overflow-hidden rounded-t-[16rem] border border-[#b7893b]/45 bg-[#f7efe4] shadow-[0_35px_80px_rgba(88,61,21,.14)]"><Image src="/brand/reformer-art.png" alt="Pratique du Pilates Reformer" fill priority className="object-cover object-[center_13%]"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#15110c]/90 to-transparent px-8 pb-8 pt-28 text-white"><p className="font-serif text-3xl">Respirez. Alignez. Avancez.</p><p className="mt-2 text-sm text-white/65">Un accompagnement précis, à votre rythme.</p></div></div></section>
      <section id="pratiques" className="bg-[#0a0a0a] py-24 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs uppercase tracking-[.3em] text-[#c79b4d]">Nos pratiques</p><h2 className="mt-5 max-w-md font-serif text-5xl leading-tight">Une méthode, quatre façons de progresser.</h2></div><div className="grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2">{[["01","Pilates au sol","Mobilité, posture et renforcement profond."],["02","Pilates Reformer","Précision et résistance sur appareil."],["03","Cours collectifs","L’énergie du groupe, en petit comité."],["04","Cours individuels","Un programme entièrement personnalisé."]].map(([n,title,desc])=><article key={n} className="group bg-[#111] p-7 transition hover:bg-[#18140e]"><div className="flex items-center justify-between text-[#b7893b]"><span className="text-xs">{n}</span><ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></div><h3 className="mt-12 text-xl font-medium">{title}</h3><p className="mt-3 text-sm leading-6 text-white/50">{desc}</p></article>)}</div></div></div></section>
    </main>
    <footer className="border-t border-[#b7893b]/25 bg-[#050505] py-10 text-white"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 px-5 sm:flex-row lg:px-8"><BrandLockup light compact/><p className="text-xs uppercase tracking-[.22em] text-white/45">Force · Équilibre · Bien-être</p></div></footer>
  </div>;
}

function SidebarItem({ icon: Icon, label, active = false }: { icon: typeof LayoutDashboard; label: string; active?: boolean }) { return <button className={`flex w-full items-center gap-3 rounded-xl px-3.5 py-3 text-left text-sm transition ${active ? "bg-[#b7893b] text-black" : "text-white/55 hover:bg-white/5 hover:text-white"}`}><Icon className="h-[18px] w-[18px]"/>{label}</button>; }

function CrmPreview() {
  const stats = [{icon:CalendarDays,value:"18",label:"Séances aujourd’hui",note:"+3 cette semaine"},{icon:UsersRound,value:"146",label:"Clientes actives",note:"+8 ce mois"},{icon:WalletCards,value:"32",label:"Forfaits à renouveler",note:"Avant le 30 sept."},{icon:CreditCard,value:"286 500 DA",label:"Chiffre du mois",note:"+12,4%"}];
  return <div className="min-h-screen bg-[#f3eee5] text-[#1c1b19]"><div className="flex min-h-[calc(100vh-68px)]"><aside className="hidden w-64 shrink-0 flex-col bg-[#080808] p-5 text-white lg:flex"><div className="border-b border-white/10 pb-6"><BrandLockup light compact/></div><nav className="mt-6 space-y-1"><SidebarItem icon={LayoutDashboard} label="Tableau de bord" active/><SidebarItem icon={CalendarDays} label="Planning"/><SidebarItem icon={UsersRound} label="Clientes"/><SidebarItem icon={WalletCards} label="Forfaits"/><SidebarItem icon={CreditCard} label="Paiements"/><SidebarItem icon={MessageCircle} label="Messages"/></nav><div className="mt-auto rounded-2xl border border-[#b7893b]/25 bg-[#b7893b]/10 p-4"><p className="text-xs uppercase tracking-[.18em] text-[#d7b66f]">Aujourd’hui</p><p className="mt-2 text-2xl font-light">18 séances</p><p className="mt-1 text-xs text-white/45">4 places encore disponibles</p></div></aside>
    <main className="min-w-0 flex-1"><header className="flex h-[78px] items-center justify-between border-b border-[#d9cdb9] bg-[#fbf8f2] px-4 sm:px-7"><div className="flex items-center gap-3"><button className="rounded-xl border border-[#d9cdb9] p-2 lg:hidden" aria-label="Menu"><Menu className="h-5 w-5"/></button><div><p className="text-xs uppercase tracking-[.18em] text-[#957035]">Jeudi 11 septembre</p><h1 className="mt-1 text-xl font-semibold">Bonjour, Lynda</h1></div></div><div className="flex items-center gap-3"><button className="hidden items-center gap-2 rounded-full border border-[#d9cdb9] bg-white px-4 py-2.5 text-sm text-[#6b645a] sm:flex"><Search className="h-4 w-4"/> Rechercher</button><button aria-label="Profil"><CircleUserRound className="h-9 w-9 text-[#9d7837]"/></button></div></header>
      <div className="space-y-7 p-4 sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-[#746d63]">Voici l’activité de votre centre.</p><h2 className="mt-1 font-serif text-4xl">Tableau de bord</h2></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#111] px-5 py-3 text-sm font-semibold text-white"><CalendarDays className="h-4 w-4 text-[#d5ae65]"/> Nouvelle réservation</button></div>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({icon:Icon,value,label,note})=><article key={label} className="rounded-2xl border border-[#ded4c3] bg-[#fffdf9] p-5 shadow-[0_10px_35px_rgba(72,54,26,.05)]"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#ede0c8] text-[#8d6729]"><Icon className="h-5 w-5"/></span><MoreHorizontal className="h-5 w-5 text-[#aaa195]"/></div><p className="mt-6 text-2xl font-semibold">{value}</p><p className="mt-1 text-sm text-[#6f685e]">{label}</p><p className="mt-4 text-xs font-medium text-[#98702e]">{note}</p></article>)}</section>
      <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-[#ded4c3] bg-[#fffdf9] p-5 sm:p-6"><div className="flex items-center justify-between"><div><h3 className="text-lg font-semibold">Planning du jour</h3><p className="mt-1 text-sm text-[#7b746a]">18 réservations · 4 places disponibles</p></div><button className="text-sm font-semibold text-[#8d6729]">Planning complet</button></div><div className="mt-6 space-y-3">{sessions.map(s=><div key={s.time} className="grid grid-cols-[52px_1fr_auto] items-center gap-3 rounded-xl border border-[#e7dfd2] p-3"><span className="text-sm font-semibold">{s.time}</span><div className="flex items-center gap-3"><span className="h-10 w-1 rounded-full bg-[#c79b4d]"/><div><p className="text-sm font-semibold">{s.title}</p><p className="text-xs text-[#837b70]">Coach {s.coach}</p></div></div><span className="rounded-full bg-[#f0e6d5] px-2.5 py-1 text-xs font-semibold text-[#765522]">{s.count}</span></div>)}</div></section>
      <section className="rounded-2xl bg-[#111] p-5 text-white sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[#c49a50]">Clientes</p><h3 className="mt-2 text-lg font-semibold">À suivre</h3></div><Heart className="h-5 w-5 text-[#c49a50]"/></div><div className="mt-6 space-y-5">{clients.map(c=><div key={c.name} className="flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#b7893b] text-xs font-bold text-black">{c.initials}</span><div className="min-w-0"><p className="truncate text-sm font-medium">{c.name}</p><p className="truncate text-xs text-white/45">{c.plan}</p></div><span className="ml-auto whitespace-nowrap text-xs text-[#d4b36f]">{c.remaining}</span></div>)}</div><button className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl border border-white/15 py-3 text-sm text-white/75">Voir toutes les clientes <ArrowRight className="h-4 w-4"/></button></section></div>
      </div></main></div></div>;
}

export default function Home() { return <Tabs defaultValue="site" className="min-h-screen gap-0"><PreviewSwitcher/><TabsContent value="site"><PublicSite/></TabsContent><TabsContent value="crm"><CrmPreview/></TabsContent></Tabs>; }
