import Link from "next/link";
import { ArrowLeft, ArrowRight, ArrowUpRight, Banknote, Clock, Search, UsersRound, WalletCards } from "lucide-react";
import type { ClientPage } from "@/domain/models/client";
import { MONTHLY_OFFERS, SINGLE_SESSION_OFFERS, COURSE_DURATION_MINUTES, COURSE_MAX_CAPACITY, QUARTERLY_DISCOUNT_PERCENT, quarterlyPrice, formatDzd } from "@/domain/models/studio-offers";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { FinanceHero, FinanceAction, financeSurface as surface, financeMuted as muted, financeLink } from "./finance-layout";

export function PackagesOverview({ page, q, after }: { page: ClientPage; q: string; after?: string }) {
  return <>
    <FinanceHero title="Forfaits & abonnements" description="Accompagnez chaque cliente : attribuez son forfait, suivez ses crédits et retrouvez ses encaissements." icon={WalletCards}>
      <FinanceAction href="#clients">Gérer le forfait d’une cliente</FinanceAction><FinanceAction href="/crm/forfaits/suivi">Échéances et crédits faibles</FinanceAction>
    </FinanceHero>
    <section aria-labelledby="offers-title" className="space-y-4">
      <div className="flex flex-wrap items-end justify-between gap-3"><div><p className={`mb-1 text-[10px] uppercase tracking-[0.2em] ${muted}`}>Le catalogue du centre</p><h2 id="offers-title" className="font-serif text-2xl">À chaque rythme, son forfait</h2></div><p className={`flex items-center gap-2 text-xs ${muted}`}><Clock size={14} />{COURSE_DURATION_MINUTES} min<UsersRound size={14} className="ml-2" />{COURSE_MAX_CAPACITY} personnes maximum</p></div>
      <div className="grid gap-4 md:grid-cols-3">
        <article className={`${surface} p-5`}><p className={`text-[10px] uppercase tracking-[0.18em] ${muted}`}>À la séance</p><h3 className="mt-2 font-serif text-2xl">Découvrir & pratiquer</h3><dl className="mt-5 space-y-4">{SINGLE_SESSION_OFFERS.map(offer => <div key={offer.id} className="flex flex-wrap items-center justify-between gap-2 border-t border-[#b7893b]/15 pt-4"><dt className={`text-xs ${muted}`}>{offer.label}</dt><dd className="text-sm font-semibold tabular-nums">{formatDzd(offer.priceDzd)}</dd></div>)}</dl></article>
        {MONTHLY_OFFERS.map(offer => <article key={offer.id} className={`${surface} relative overflow-hidden p-5`}><p className={`text-[10px] uppercase tracking-[0.18em] ${muted}`}>Abonnement mensuel</p><h3 className="mt-2 font-serif text-2xl">{offer.sessionsPerMonth} séances <span className={`font-sans text-xs ${muted}`}>/ mois</span></h3><p className="mt-5 font-serif text-3xl tabular-nums">{formatDzd(offer.priceDzd)}</p><div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-[#b7893b]/15 pt-4"><div><p className={`text-[11px] ${muted}`}>Tarif trimestriel</p><p className="mt-1 text-sm font-semibold tabular-nums">{formatDzd(quarterlyPrice(offer.priceDzd))} <span className={`text-[10px] font-normal ${muted}`}>/ 3 mois</span></p></div><span className="rounded-full bg-[#b7893b]/10 px-2.5 py-1.5 text-xs text-[#886125] dark:text-[#e0bd80]">−{QUARTERLY_DISCOUNT_PERCENT} %</span></div></article>)}
      </div>
      <p className={`flex items-start gap-2 text-xs leading-5 ${muted}`}><Banknote size={16} className="mt-0.5 shrink-0" />Paiement en espèces. Acomptes et solde restant suivis dans le journal de chaque abonnement.</p>
    </section>
    <section id="clients" className={`${surface} scroll-mt-6 overflow-hidden`} aria-labelledby="package-clients-title">
      <div className="space-y-5 border-b border-[#b7893b]/15 p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="package-clients-title" className="font-serif text-2xl">Les forfaits de vos clientes</h2><p className={`mt-2 text-xs ${muted}`}>Sélectionnez un dossier pour gérer les abonnements, crédits et encaissements.</p></div><span className={`rounded-full bg-[#b7893b]/10 px-3 py-1.5 text-xs ${muted}`}>{page.clients.length} cliente(s) sur cette page</span></div>
        <form action="/crm/forfaits" className="flex flex-wrap items-end gap-3"><div className="min-w-40 flex-1"><label htmlFor="package-client-search" className={`mb-2 block text-xs ${muted}`}>Rechercher une cliente</label><div className="relative"><Search size={16} className={`absolute left-3 top-3.5 ${muted}`} /><Input id="package-client-search" name="q" defaultValue={q} maxLength={254} placeholder="Nom ou adresse e-mail…" className="h-11 rounded-xl pl-9" /></div></div><Button type="submit" className="h-11 rounded-xl">Rechercher</Button>{q && <Link className={financeLink} href="/crm/forfaits#clients">Effacer</Link>}</form>
      </div>
      {page.clients.length === 0 ? <div className="px-6 py-16 text-center"><UsersRound size={32} strokeWidth={1.2} className="mx-auto mb-4 text-[#b7893b]" /><h3 className="font-serif text-2xl">Aucune cliente trouvée</h3><p className={`mt-2 text-sm ${muted}`}>{q ? "Essayez un autre nom ou une autre adresse e-mail." : "Les dossiers de vos clientes apparaîtront ici."}</p><Link className={`${financeLink} mt-5`} href={q ? "/crm/forfaits#clients" : "/crm/clientes"}>{q ? "Voir les clientes" : "Ouvrir l’annuaire"}<ArrowRight size={14} /></Link></div> : <ul className="grid sm:grid-cols-2">{page.clients.map(client => <li key={client.id} className="min-w-0 border-b border-[#b7893b]/10 sm:odd:border-r"><Link href={`/crm/clientes/${client.id}/forfaits`} className="group flex h-full items-start gap-3 p-5 transition hover:bg-[#b7893b]/5 focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[#b7893b] sm:p-6"><span aria-hidden="true" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-[#b7893b]/15 bg-[#b7893b]/10 font-serif text-lg text-[#946b2f] dark:text-[#dbb97e]">{client.name.trim().split(/\s+/).slice(0, 2).map(word => word[0]).join("").toUpperCase()}</span><div className="min-w-0 flex-1"><h3 className="break-words text-sm font-semibold">{client.name}</h3><p className={`mt-1.5 break-all text-xs ${muted}`}>{client.email || "Adresse e-mail non renseignée"}</p><span className="mt-4 inline-flex items-center gap-2 text-xs font-medium text-[#946b2f] group-hover:underline dark:text-[#dbb97e]">Gérer les forfaits<ArrowUpRight size={14} /></span></div></Link></li>)}</ul>}
      <nav className="flex flex-wrap items-center justify-between gap-3 p-5" aria-label="Pagination des clientes"><p className={`text-xs ${muted}`}>{page.next ? "D’autres clientes sont disponibles." : "Fin de la liste"}</p><div className="flex flex-wrap gap-2">{after && <Link className={financeLink} href={`/crm/forfaits?${new URLSearchParams({ q })}`}><ArrowLeft size={14} />Première page</Link>}{page.next && <Link className={financeLink} href={`/crm/forfaits?${new URLSearchParams({ q, after: page.next })}`}>Page suivante<ArrowRight size={14} /></Link>}</div></nav>
    </section>
  </>;
}
