import type { ReactNode } from "react";
import { ArrowRight, CalendarDays, CircleUserRound, CreditCard, Heart, LayoutDashboard, MessageCircle, Search, UsersRound, WalletCards } from "lucide-react";
import { BrandLockup } from "@/components/brand/brand-lockup";
import type { DaySummary } from "@/domain/models/dashboard";
import Link from "next/link";
import type { ClientProfile } from "@/domain/models/client";
import { studioDateTime, type SessionView } from "@/domain/models/planning";

function SidebarItem({ icon: Icon, label, active = false }: { icon: typeof LayoutDashboard; label: string; active?: boolean }) { const className = `flex w-full items-center gap-3 rounded-xl px-3.5 py-3 text-left text-sm transition ${active ? "bg-[#b7893b] text-black" : "text-white/55 hover:bg-white/5 hover:text-white"}`; const href = label === "Tableau de bord" ? "/crm" : label === "Clientes" ? "/crm/clientes" : label === "Planning" ? "/crm/planning" : label === "Encaissements" ? "/crm/encaissements" : label === "Forfaits" ? "/crm/forfaits" : undefined; return href ? <Link href={href} className={className}><Icon className="h-[18px] w-[18px]"/>{label}</Link> : <span aria-disabled="true" className="flex w-full items-center gap-3 px-3.5 py-3 text-sm text-white/35"><Icon className="h-[18px] w-[18px]"/>{label}<small className="ml-auto">À venir</small></span>; }

export function CrmPreview({ clients, planning, dayLabel, summary, attendance }: { attendance: ReactNode; summary: DaySummary; clients: ClientProfile[]; planning: SessionView[]; dayLabel: string }) {
  const stats = [
    { icon: CalendarDays, value: summary.sessions, label: "Séances maintenues", note: `${summary.cancelled} séance(s) annulée(s) exclue(s)`, key: "sessions" },
    { icon: UsersRound, value: summary.bookings, label: "Réservations du jour", note: "Places réservées, pas clientes uniques", key: "bookings" },
    { icon: WalletCards, value: summary.available, label: "Places non réservées", note: "Sur les séances maintenues du jour", key: "available" },
    { icon: CalendarDays, value: summary.occupancy === null ? "—" : `${summary.occupancy} %`, label: "Taux de remplissage", note: "Réservations / capacité du jour", key: "occupancy" },
  ];
  return <div className="min-h-screen bg-[#f3eee5] text-[#1c1b19]"><div className="flex min-h-[calc(100vh-68px)]"><aside className="hidden w-64 shrink-0 flex-col bg-[#080808] p-5 text-white lg:flex"><div className="border-b border-white/10 pb-6"><BrandLockup light compact/></div><nav className="mt-6 space-y-1"><SidebarItem icon={LayoutDashboard} label="Tableau de bord" active/><SidebarItem icon={CalendarDays} label="Planning"/><SidebarItem icon={UsersRound} label="Clientes"/><SidebarItem icon={WalletCards} label="Forfaits"/><SidebarItem icon={CreditCard} label="Encaissements"/><SidebarItem icon={MessageCircle} label="Messages"/></nav><div className="mt-auto rounded-2xl border border-[#b7893b]/25 bg-[#b7893b]/10 p-4"><p className="text-xs uppercase tracking-[.18em] text-[#d7b66f]">Aujourd’hui</p><p className="mt-2 text-2xl font-light">Planning</p><p className="mt-1 text-xs text-white/45">Séances du centre</p></div></aside>
    <main className="min-w-0 flex-1"><header className="flex h-[78px] items-center justify-between border-b border-[#d9cdb9] bg-[#fbf8f2] px-4 sm:px-7"><div className="flex items-center gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-[#957035]">{dayLabel}</p><h1 className="mt-1 text-xl font-semibold">Bonjour</h1></div></div><div className="flex items-center gap-3"><Link href="/crm/clientes" className="hidden items-center gap-2 rounded-full border border-[#d9cdb9] bg-white px-4 py-2.5 text-sm text-[#6b645a] sm:flex"><Search className="h-4 w-4"/> Rechercher une cliente</Link><Link href="/crm/acces" aria-label="Gestion des accès"><CircleUserRound className="h-9 w-9 text-[#9d7837]"/></Link></div></header>
      <div className="space-y-7 p-4 sm:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-[#746d63]">Journée complète, séances passées et à venir. Actualisez la page pour mettre à jour les chiffres.</p><h2 className="mt-1 font-serif text-4xl">Tableau de bord</h2></div><Link href="/crm/planning" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#111] px-5 py-3 text-sm font-semibold text-white"><CalendarDays className="h-4 w-4 text-[#d5ae65]"/> Gérer les séances</Link></div>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({icon:Icon,value,label,note,key})=><article key={label} className="rounded-2xl border border-[#ded4c3] bg-[#fffdf9] p-5 shadow-[0_10px_35px_rgba(72,54,26,.05)]"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#ede0c8] text-[#8d6729]"><Icon className="h-5 w-5"/></span></div><p data-testid={`dashboard-${key}`} className="mt-6 text-2xl font-semibold">{value}</p><p className="mt-1 text-sm text-[#6f685e]">{label}</p><p className="mt-4 text-xs font-medium text-[#98702e]">{note}</p></article>)}</section>
      {attendance}
      <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><section className="rounded-2xl border border-[#ded4c3] bg-[#fffdf9] p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold">Planning du jour</h3><p className="mt-1 text-sm text-[#7b746a]">Séances enregistrées · Heure d’Alger</p></div><Link href="/crm/planning" className="text-sm font-semibold text-[#8d6729]">Planning complet</Link></div><div className="mt-6 space-y-3">{planning.length === 0 && <p className="text-sm text-muted-foreground">Aucune séance enregistrée aujourd’hui.</p>}{planning.map(({session:s})=><Link href={`/crm/planning/${s.id}`} key={s.id} className="grid grid-cols-[52px_1fr_auto] items-center gap-3 rounded-xl border border-[#e7dfd2] p-3"><span className="text-sm font-semibold">{studioDateTime(s.startsAt).slice(11)}</span><div className="flex min-w-0 items-center gap-3"><span className="h-10 w-1 shrink-0 rounded-full bg-[#c79b4d]"/><div className="min-w-0"><p className="break-words text-sm font-semibold">{s.title}</p><p className="break-words text-xs text-[#837b70]">Coach {s.instructor}</p></div></div><span className="rounded-full bg-[#f0e6d5] px-2.5 py-1 text-xs font-semibold text-[#765522]">{s.status === "cancelled" ? "Annulée" : `${s.bookedCount}/${s.capacity}`}</span></Link>)}</div></section>
      <section className="rounded-2xl bg-[#111] p-5 text-white sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-[#c49a50]">Clientes</p><h3 className="mt-2 text-lg font-semibold">Annuaire du centre</h3></div><Heart className="h-5 w-5 text-[#c49a50]"/></div><div className="mt-6 space-y-5">{clients.length === 0 && <p className="text-sm text-white/60">Créez votre première fiche cliente.</p>}{clients.map(c=><Link href={`/crm/clientes/${c.id}`} key={c.id} className="flex items-center gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#b7893b] text-xs font-bold text-black">{c.name.split(/\s+/).slice(0, 2).map(word => word[0]).join("").toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-medium">{c.name}</p><p className="truncate text-xs text-white/45">{c.email}</p></div><span className="ml-auto whitespace-nowrap text-xs text-[#d4b36f]">{c.status === "active" ? "Active" : "Inactive"}</span></Link>)}</div><Link href="/crm/clientes" className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl border border-white/15 py-3 text-sm text-white/75">Voir toutes les clientes <ArrowRight className="h-4 w-4"/></Link></section></div>
      </div></main></div></div>;
}
