import Link from "next/link";
import { historyLabels, type ClientHistoryPage } from "@/domain/models/client-history";
import { displaySessionTime } from "@/domain/models/planning";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
export function ClientHistory({ page, basePath, admin, after }: { page: ClientHistoryPage; basePath: string; admin: boolean; after?: string }) {
  const { summary } = page;
  return <div className="space-y-6"><form action={basePath} className="flex flex-wrap items-end gap-4 rounded-2xl border bg-[#fffdf9] p-5"><div className="space-y-2"><label htmlFor="history-month" className="block text-sm">Mois des séances</label><Input id="history-month" type="month" name="month" defaultValue={page.month} key={page.month} min="2000-01" max="2100-12" required /></div><Button type="submit">Afficher le mois</Button><p className="text-sm text-muted-foreground">Dates et horaires d’Alger.</p></form><section aria-label="Assiduité du mois" className="space-y-4"><h2 className="font-serif text-2xl">Assiduité du mois sélectionné</h2><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Présences", summary.present], ["Absences", summary.absent], ["À renseigner", summary.unmarked], ["Taux de présence", summary.attendanceRate === null ? "Non calculable" : `${summary.attendanceRate} %`]].map(([label, value]) => <div key={label} className="rounded-2xl border border-[#ded4c3] bg-[#fffdf9] p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-xl font-medium text-[#8b652b]">{value}</p></div>)}</div><p className="text-sm leading-6 text-muted-foreground">Taux = présences ÷ (présences + absences), uniquement pour les cours terminés et renseignés. Les indicateurs couvrent tout le mois, y compris les pages suivantes.</p><p className="text-sm">{summary.upcoming} à venir · {summary["in-progress"]} en cours · {summary.cancelled} réservation(s) annulée(s) · {summary["session-cancelled"]} séance(s) annulée(s)</p></section><section className="space-y-3" aria-label="Séances de la cliente"><h2 className="font-serif text-2xl">Séances et réservations</h2>{page.entries.length === 0 && <p className="rounded-2xl border border-dashed p-6">Aucune réservation pour ce mois.</p>}{page.entries.map((entry) => <article key={entry.id} className="space-y-3 rounded-2xl border border-[#ded4c3] bg-[#fffdf9] p-5"><p className="text-sm text-[#8b652b]">{displaySessionTime(entry.startsAt)}</p><h3 className="font-serif text-2xl">{entry.title}</h3><p className="text-sm text-muted-foreground">Coach {entry.instructor} · {entry.durationMinutes} min</p><p className="font-medium">{historyLabels[entry.status]}</p>{admin && <Link href={`/crm/planning/${entry.id}`} className="inline-block text-sm underline">Ouvrir la séance et sa feuille de présence</Link>}</article>)}</section><nav aria-label="Pagination des séances" className="flex flex-wrap gap-6 text-sm underline">{after && <Link href={`${basePath}?${new URLSearchParams({ month: page.month })}`}>Première page du mois</Link>}{page.next && <Link href={`${basePath}?${new URLSearchParams({ month: page.month, after: page.next })}`}>Séances suivantes</Link>}</nav></div>;
}
