import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Menu } from "lucide-react";
import { StudioPricing } from "@/features/packages/studio-pricing";
import { COURSE_MAX_CAPACITY } from "@/domain/models/studio-offers";
import { BrandLockup } from "@/components/brand/brand-lockup";

export function PublicSite() {
  return <div className="min-h-screen bg-[#f8f2e9] text-[#1d1d1d]">
    <header className="border-b border-[#cdae72]/30 bg-[#fcf8f1]/95"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><BrandLockup compact/><nav className="hidden items-center gap-8 text-sm lg:flex"><a href="#studio">Le studio</a><a href="#pratiques">Nos pratiques</a><a href="#planning">Planning</a><a href="#tarifs">Tarifs</a></nav><div className="flex items-center gap-2"><Link href="/espace-cliente" className="hidden rounded-full px-4 py-2.5 text-sm sm:block">Espace cliente</Link><button className="rounded-full bg-[#111] px-5 py-3 text-sm font-semibold text-white transition hover:bg-[#b7893b] hover:text-black">Réserver</button><button className="p-2 lg:hidden" aria-label="Ouvrir le menu"><Menu/></button></div></div></header>
    <main>
      <section id="studio" className="mx-auto grid min-h-[680px] max-w-7xl items-center gap-10 px-5 py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-20"><div className="relative z-10"><div className="mb-8 inline-flex items-center gap-3 text-xs font-semibold uppercase tracking-[.28em] text-[#9a712e]"><span className="h-px w-10 bg-[#b7893b]"/> Studio féminin à Alger</div><h1 className="max-w-3xl font-serif text-[clamp(3.4rem,7vw,6.8rem)] font-light leading-[.92] tracking-[-.04em]">La force dans<br/><em className="font-light text-[#b7893b]">l’équilibre.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#676056]">Pilates au sol et Reformer dans un espace pensé pour vous recentrer, progresser et prendre soin de votre corps.</p><div className="mt-9 flex flex-wrap items-center gap-4"><button className="group inline-flex items-center gap-3 rounded-full bg-[#b7893b] px-6 py-4 font-semibold text-black transition hover:bg-[#d7b66f]">Découvrir nos cours <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></button><button className="rounded-full border border-[#b7893b]/50 px-6 py-4 font-semibold">Voir le planning</button></div><div className="mt-12 grid max-w-xl grid-cols-3 gap-4 border-t border-[#cdae72]/35 pt-7">{[["4","pratiques"],["100%","féminin"],[String(COURSE_MAX_CAPACITY),"places max."]].map(([value,label])=><div key={label}><div className="font-serif text-3xl text-[#99702d]">{value}</div><div className="mt-1 text-xs uppercase tracking-[.16em] text-[#71695e]">{label}</div></div>)}</div></div><div className="relative mx-auto h-[610px] w-full max-w-[520px] overflow-hidden rounded-t-[16rem] border border-[#b7893b]/45 bg-[#f7efe4] shadow-[0_35px_80px_rgba(88,61,21,.14)]"><Image src="/brand/reformer-art.png" alt="Pratique du Pilates Reformer" fill priority sizes="(min-width: 1024px) 520px, 100vw" className="object-cover object-[center_13%]"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#15110c]/90 to-transparent px-8 pb-8 pt-28 text-white"><p className="font-serif text-3xl">Respirez. Alignez. Avancez.</p><p className="mt-2 text-sm text-white/65">Un accompagnement précis, à votre rythme.</p></div></div></section>
      <section id="pratiques" className="bg-[#0a0a0a] py-24 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs uppercase tracking-[.3em] text-[#c79b4d]">Nos pratiques</p><h2 className="mt-5 max-w-md font-serif text-5xl leading-tight">Une méthode, quatre façons de progresser.</h2></div><div className="grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 sm:grid-cols-2">{[["01","Pilates au sol","Mobilité, posture et renforcement profond."],["02","Pilates Reformer","Précision et résistance sur appareil."],["03","Cours collectifs","L’énergie du groupe, en petit comité."],["04","Cours individuels","Un programme entièrement personnalisé."]].map(([n,title,desc])=><article key={n} className="group bg-[#111] p-7 transition hover:bg-[#18140e]"><div className="flex items-center justify-between text-[#b7893b]"><span className="text-xs">{n}</span><ArrowRight className="h-4 w-4 transition group-hover:translate-x-1"/></div><h3 className="mt-12 text-xl font-medium">{title}</h3><p className="mt-3 text-sm leading-6 text-white/50">{desc}</p></article>)}</div></div></div></section>
      <div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><StudioPricing /></div>
    </main>
    <footer className="border-t border-[#b7893b]/25 bg-[#050505] py-10 text-white"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 px-5 sm:flex-row lg:px-8"><BrandLockup light compact/><p className="text-xs uppercase tracking-[.22em] text-white/45">Force · Équilibre · Bien-être</p></div></footer>
  </div>;
}
